import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css';
import Homeslide from '@/component/Homeslide';
import HomeProduct1 from '@/component/HomeProduct1';
import HomeProduct from '@/component/HomeProduct';
 function Home() {
  return (
    <>
      <Head>
        <title>Insole</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>  
      <Homeslide/>
      <HomeProduct/>
      <HomeProduct1/>
    </>
  )
}

export default Home
